<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IncludeTestHost>true</IncludeTestHost>
    <IncludeTestHelpers>true</IncludeTestHelpers>
    <IncludeSutApp>true</IncludeSutApp>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(LocalRoot)\Eventuous.Azure.CosmosDb\Eventuous.Azure.CosmosDb.csproj" />
    <ProjectReference Include="$(DiagRoot)\Eventuous.Diagnostics.OpenTelemetry\Eventuous.Diagnostics.OpenTelemetry.csproj" />
    <ProjectReference Include="$(DiagRoot)\Eventuous.Diagnostics.Logging\Eventuous.Diagnostics.Logging.csproj" />
    <ProjectReference Include="$(ExtRoot)\Eventuous.Extensions.DependencyInjection\Eventuous.Extensions.DependencyInjection.csproj" />
    <ProjectReference Include="$(CoreTestRoot)\Eventuous.Tests.Persistence.Base\Eventuous.Tests.Persistence.Base.csproj" />
    <ProjectReference Include="$(SrcRoot)\Diagnostics\test\Eventuous.Tests.OpenTelemetry\Eventuous.Tests.OpenTelemetry.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.CosmosDb" />
  </ItemGroup>
</Project>


