version: '3.7'

services:

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"  # Blob
      - "10001:10001"  # Queue
      - "10002:10002"  # Table
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"

  mongo:
    container_name: esdemo-mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  zipkin:
    image: openzipkin/zipkin
    container_name: esdemo-zipkin
    ports:
      - "9411:9411"

  prometheus:
    container_name: esdemo-prometheus
    image: prom/prometheus:v2.17.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: esdemo-grafana
    image: grafana/grafana:6.7.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana/dashboards:/dashboards

  seq:
    image: datalust/seq:latest
    container_name: esdemo-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

networks:
  default:
    name: eventuous-demo
